language: perl

matrix:
  include:
  - perl: "5.30"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls Test::LWP::UserAgent HTTP::Response

script:
  perl Build.PL && ./Build build && cover -test -report coveralls
